<?php

return [
    'brand' => [
        'name' => env('ADMIN_BRAND_NAME', 'Mahaprabhu Tech'),
        'company' => env('ADMIN_COMPANY_NAME', 'Mahaprabhu Tech Innovation Private Limited'),
        'primary' => '#EF1717',
        'primary_dark' => '#B80F16',
        'black' => '#111111',
        'background' => '#F7F7F8',
    ],

    /*
    |--------------------------------------------------------------------------
    | Website content modules
    |--------------------------------------------------------------------------
    |
    | The admin panel checks the live database before displaying a module.
    | Field aliases let the same panel work when an existing project uses
    | title/name, image/thumbnail, status/is_active, etc.
    |
    */
    'modules' => [
        'blog-posts' => [
            'label' => 'Blog Posts',
            'singular' => 'Blog Post',
            'table' => 'blog_posts',
            'icon' => 'newspaper',
            'description' => 'Publish company news, articles and announcements.',
            'search' => ['title', 'slug', 'excerpt', 'content'],
            'title_columns' => ['title', 'name'],
            'status_columns' => ['status', 'is_active', 'published'],
            'date_columns' => ['published_at', 'created_at'],
            'fields' => [
                ['columns' => ['title', 'name'], 'label' => 'Title', 'type' => 'text', 'required' => true, 'span' => 2],
                ['columns' => ['slug'], 'label' => 'Slug', 'type' => 'text', 'help' => 'Leave empty to generate from the title.'],
                ['columns' => ['category'], 'label' => 'Category', 'type' => 'text'],
                ['columns' => ['excerpt', 'short_description', 'summary'], 'label' => 'Short Summary', 'type' => 'textarea', 'span' => 2],
                ['columns' => ['content', 'description', 'body'], 'label' => 'Article Content', 'type' => 'richtext', 'span' => 2],
                ['columns' => ['featured_image', 'image', 'thumbnail'], 'label' => 'Featured Image', 'type' => 'image'],
                ['columns' => ['published_at'], 'label' => 'Publish Date', 'type' => 'datetime-local'],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived']],
                ['columns' => ['is_active', 'published'], 'label' => 'Visible on Website', 'type' => 'boolean'],
                ['columns' => ['meta_title'], 'label' => 'SEO Title', 'type' => 'text', 'span' => 2],
                ['columns' => ['meta_description'], 'label' => 'SEO Description', 'type' => 'textarea', 'span' => 2],
            ],
        ],

        'services' => [
            'label' => 'Services',
            'singular' => 'Service',
            'table' => 'services',
            'icon' => 'briefcase',
            'description' => 'Manage the services shown on the corporate website.',
            'search' => ['title', 'name', 'short_description', 'description'],
            'title_columns' => ['title', 'name', 'service_name'],
            'status_columns' => ['status', 'is_active'],
            'date_columns' => ['created_at'],
            'fields' => [
                ['columns' => ['title', 'name', 'service_name'], 'label' => 'Service Name', 'type' => 'text', 'required' => true, 'span' => 2],
                ['columns' => ['slug'], 'label' => 'Slug', 'type' => 'text'],
                ['columns' => ['icon'], 'label' => 'Icon Name', 'type' => 'text', 'help' => 'Optional icon class/name used by your frontend.'],
                ['columns' => ['short_description', 'excerpt', 'summary'], 'label' => 'Short Description', 'type' => 'textarea', 'span' => 2],
                ['columns' => ['description', 'content'], 'label' => 'Full Description', 'type' => 'richtext', 'span' => 2],
                ['columns' => ['image', 'featured_image', 'thumbnail'], 'label' => 'Service Image', 'type' => 'image'],
                ['columns' => ['sort_order', 'display_order', 'order'], 'label' => 'Display Order', 'type' => 'number'],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
                ['columns' => ['is_active'], 'label' => 'Active', 'type' => 'boolean'],
            ],
        ],

        'projects' => [
            'label' => 'Projects',
            'singular' => 'Project',
            'table' => 'projects',
            'icon' => 'folder',
            'description' => 'Showcase completed and ongoing company projects.',
            'search' => ['title', 'name', 'client_name', 'description'],
            'title_columns' => ['title', 'name', 'project_name'],
            'status_columns' => ['status', 'is_active'],
            'date_columns' => ['completed_at', 'created_at'],
            'fields' => [
                ['columns' => ['title', 'name', 'project_name'], 'label' => 'Project Name', 'type' => 'text', 'required' => true, 'span' => 2],
                ['columns' => ['slug'], 'label' => 'Slug', 'type' => 'text'],
                ['columns' => ['client_name', 'client'], 'label' => 'Client', 'type' => 'text'],
                ['columns' => ['category'], 'label' => 'Category', 'type' => 'text'],
                ['columns' => ['project_url', 'website_url', 'url'], 'label' => 'Project URL', 'type' => 'url'],
                ['columns' => ['short_description', 'excerpt', 'summary'], 'label' => 'Short Description', 'type' => 'textarea', 'span' => 2],
                ['columns' => ['description', 'content'], 'label' => 'Full Description', 'type' => 'richtext', 'span' => 2],
                ['columns' => ['featured_image', 'image', 'thumbnail'], 'label' => 'Cover Image', 'type' => 'image'],
                ['columns' => ['completed_at', 'project_date'], 'label' => 'Completion Date', 'type' => 'date'],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['ongoing' => 'Ongoing', 'completed' => 'Completed', 'draft' => 'Draft']],
                ['columns' => ['is_active'], 'label' => 'Visible', 'type' => 'boolean'],
            ],
            'gallery_table' => 'project_images',
        ],

        'team-members' => [
            'label' => 'Team Members',
            'singular' => 'Team Member',
            'table' => 'team_members',
            'icon' => 'users',
            'description' => 'Manage leadership and team profiles.',
            'search' => ['name', 'designation', 'position', 'bio'],
            'title_columns' => ['name', 'full_name'],
            'status_columns' => ['status', 'is_active'],
            'date_columns' => ['created_at'],
            'fields' => [
                ['columns' => ['name', 'full_name'], 'label' => 'Full Name', 'type' => 'text', 'required' => true],
                ['columns' => ['designation', 'position', 'role'], 'label' => 'Designation', 'type' => 'text', 'required' => true],
                ['columns' => ['photo', 'image', 'profile_image'], 'label' => 'Profile Photo', 'type' => 'image'],
                ['columns' => ['email'], 'label' => 'Email', 'type' => 'email'],
                ['columns' => ['phone', 'mobile'], 'label' => 'Phone', 'type' => 'text'],
                ['columns' => ['linkedin_url', 'linkedin'], 'label' => 'LinkedIn URL', 'type' => 'url'],
                ['columns' => ['bio', 'description'], 'label' => 'Profile / Bio', 'type' => 'textarea', 'span' => 2],
                ['columns' => ['sort_order', 'display_order', 'order'], 'label' => 'Display Order', 'type' => 'number'],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
                ['columns' => ['is_active'], 'label' => 'Active', 'type' => 'boolean'],
            ],
        ],

        'jobs' => [
            'label' => 'Job Openings',
            'singular' => 'Job Opening',
            'table' => 'jobs',
            'icon' => 'briefcase',
            'description' => 'Publish and manage vacancies on the careers page.',
            'search' => ['title', 'job_title', 'position', 'location', 'description'],
            'title_columns' => ['title', 'job_title', 'position'],
            'status_columns' => ['status', 'is_active'],
            'date_columns' => ['closing_date', 'created_at'],
            'fields' => [
                ['columns' => ['title', 'job_title', 'position'], 'label' => 'Job Title', 'type' => 'text', 'required' => true, 'span' => 2],
                ['columns' => ['slug'], 'label' => 'Slug', 'type' => 'text'],
                ['columns' => ['department'], 'label' => 'Department', 'type' => 'text'],
                ['columns' => ['location'], 'label' => 'Location', 'type' => 'text'],
                ['columns' => ['employment_type', 'job_type', 'type'], 'label' => 'Employment Type', 'type' => 'select', 'options' => ['full-time' => 'Full Time', 'part-time' => 'Part Time', 'contract' => 'Contract', 'internship' => 'Internship']],
                ['columns' => ['experience', 'experience_required'], 'label' => 'Experience Required', 'type' => 'text'],
                ['columns' => ['short_description', 'summary'], 'label' => 'Short Summary', 'type' => 'textarea', 'span' => 2],
                ['columns' => ['description', 'content'], 'label' => 'Job Description', 'type' => 'richtext', 'span' => 2],
                ['columns' => ['requirements'], 'label' => 'Requirements', 'type' => 'textarea', 'span' => 2],
                ['columns' => ['closing_date', 'last_date'], 'label' => 'Application Closing Date', 'type' => 'date'],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['draft' => 'Draft', 'open' => 'Open', 'closed' => 'Closed']],
                ['columns' => ['is_active'], 'label' => 'Visible', 'type' => 'boolean'],
            ],
        ],

        'testimonials' => [
            'label' => 'Testimonials',
            'singular' => 'Testimonial',
            'table' => 'testimonials',
            'icon' => 'message-square',
            'description' => 'Manage client feedback displayed on the website.',
            'search' => ['client_name', 'name', 'company', 'message', 'content'],
            'title_columns' => ['client_name', 'name', 'author_name'],
            'status_columns' => ['status', 'is_active'],
            'date_columns' => ['created_at'],
            'fields' => [
                ['columns' => ['client_name', 'name', 'author_name'], 'label' => 'Client Name', 'type' => 'text', 'required' => true],
                ['columns' => ['company', 'company_name'], 'label' => 'Company', 'type' => 'text'],
                ['columns' => ['designation', 'position'], 'label' => 'Designation', 'type' => 'text'],
                ['columns' => ['photo', 'image', 'avatar'], 'label' => 'Client Photo', 'type' => 'image'],
                ['columns' => ['message', 'content', 'testimonial', 'description'], 'label' => 'Testimonial', 'type' => 'textarea', 'required' => true, 'span' => 2],
                ['columns' => ['rating'], 'label' => 'Rating', 'type' => 'number', 'min' => 1, 'max' => 5],
                ['columns' => ['sort_order', 'display_order', 'order'], 'label' => 'Display Order', 'type' => 'number'],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
                ['columns' => ['is_active'], 'label' => 'Active', 'type' => 'boolean'],
            ],
        ],

        'enquiries' => [
            'label' => 'Enquiries',
            'singular' => 'Enquiry',
            'table' => 'enquiries',
            'icon' => 'inbox',
            'description' => 'Review enquiries submitted from the contact form.',
            'search' => ['name', 'email', 'mobile', 'phone', 'company', 'service', 'message'],
            'title_columns' => ['name', 'company', 'email'],
            'status_columns' => ['status'],
            'date_columns' => ['created_at'],
            'create' => false,
            'delete' => false,
            'fields' => [
                ['columns' => ['name'], 'label' => 'Name', 'type' => 'text', 'readonly' => true],
                ['columns' => ['email'], 'label' => 'Email', 'type' => 'email', 'readonly' => true],
                ['columns' => ['mobile', 'phone'], 'label' => 'Mobile', 'type' => 'text', 'readonly' => true],
                ['columns' => ['company'], 'label' => 'Company', 'type' => 'text', 'readonly' => true],
                ['columns' => ['service'], 'label' => 'Interested Service', 'type' => 'text', 'readonly' => true],
                ['columns' => ['budget_range', 'budget'], 'label' => 'Budget Range', 'type' => 'text', 'readonly' => true],
                ['columns' => ['message'], 'label' => 'Message', 'type' => 'textarea', 'readonly' => true, 'span' => 2],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['new' => 'New', 'contacted' => 'Contacted', 'qualified' => 'Qualified', 'closed' => 'Closed', 'spam' => 'Spam']],
                ['columns' => ['admin_notes', 'notes'], 'label' => 'Admin Notes', 'type' => 'textarea', 'span' => 2],
            ],
        ],

        'job-applications' => [
            'label' => 'Job Applications',
            'singular' => 'Job Application',
            'table' => 'job_applications',
            'icon' => 'user-check',
            'description' => 'Review candidates who applied from the careers page.',
            'search' => ['name', 'full_name', 'email', 'phone', 'position', 'job_title'],
            'title_columns' => ['name', 'full_name', 'email'],
            'status_columns' => ['status'],
            'date_columns' => ['created_at'],
            'create' => false,
            'delete' => false,
            'fields' => [
                ['columns' => ['name', 'full_name'], 'label' => 'Candidate Name', 'type' => 'text', 'readonly' => true],
                ['columns' => ['email'], 'label' => 'Email', 'type' => 'email', 'readonly' => true],
                ['columns' => ['phone', 'mobile'], 'label' => 'Phone', 'type' => 'text', 'readonly' => true],
                ['columns' => ['position', 'job_title', 'applied_for'], 'label' => 'Applied Position', 'type' => 'text', 'readonly' => true],
                ['columns' => ['experience', 'experience_years'], 'label' => 'Experience', 'type' => 'text', 'readonly' => true],
                ['columns' => ['resume', 'resume_path', 'cv'], 'label' => 'Resume', 'type' => 'file', 'readonly' => true],
                ['columns' => ['cover_letter', 'message'], 'label' => 'Cover Letter', 'type' => 'textarea', 'readonly' => true, 'span' => 2],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['new' => 'New', 'reviewing' => 'Reviewing', 'shortlisted' => 'Shortlisted', 'interview' => 'Interview', 'selected' => 'Selected', 'rejected' => 'Rejected']],
                ['columns' => ['admin_notes', 'notes'], 'label' => 'Admin Notes', 'type' => 'textarea', 'span' => 2],
            ],
        ],

        'quotations' => [
            'label' => 'Quotation Requests',
            'singular' => 'Quotation Request',
            'table' => 'quotations',
            'icon' => 'file-text',
            'description' => 'Track requests for estimates and proposals.',
            'search' => ['name', 'email', 'phone', 'company', 'service', 'project_type', 'message'],
            'title_columns' => ['name', 'company', 'email'],
            'status_columns' => ['status'],
            'date_columns' => ['created_at'],
            'create' => false,
            'delete' => false,
            'fields' => [
                ['columns' => ['name'], 'label' => 'Name', 'type' => 'text', 'readonly' => true],
                ['columns' => ['email'], 'label' => 'Email', 'type' => 'email', 'readonly' => true],
                ['columns' => ['phone', 'mobile'], 'label' => 'Phone', 'type' => 'text', 'readonly' => true],
                ['columns' => ['company'], 'label' => 'Company', 'type' => 'text', 'readonly' => true],
                ['columns' => ['service', 'project_type'], 'label' => 'Service / Project', 'type' => 'text', 'readonly' => true],
                ['columns' => ['budget', 'budget_range'], 'label' => 'Budget', 'type' => 'text', 'readonly' => true],
                ['columns' => ['message', 'requirements', 'description'], 'label' => 'Requirements', 'type' => 'textarea', 'readonly' => true, 'span' => 2],
                ['columns' => ['status'], 'label' => 'Status', 'type' => 'select', 'options' => ['new' => 'New', 'reviewing' => 'Reviewing', 'quoted' => 'Quoted', 'accepted' => 'Accepted', 'closed' => 'Closed']],
                ['columns' => ['admin_notes', 'notes'], 'label' => 'Admin Notes', 'type' => 'textarea', 'span' => 2],
            ],
        ],
    ],

    'settings' => [
        'company_name' => ['label' => 'Company Name', 'type' => 'text', 'group' => 'Company'],
        'company_tagline' => ['label' => 'Tagline', 'type' => 'text', 'group' => 'Company'],
        'company_description' => ['label' => 'Company Description', 'type' => 'textarea', 'group' => 'Company'],
        'email' => ['label' => 'Public Email', 'type' => 'email', 'group' => 'Contact'],
        'phone' => ['label' => 'Public Phone', 'type' => 'text', 'group' => 'Contact'],
        'address' => ['label' => 'Office Address', 'type' => 'textarea', 'group' => 'Contact'],
        'facebook_url' => ['label' => 'Facebook URL', 'type' => 'url', 'group' => 'Social Media'],
        'linkedin_url' => ['label' => 'LinkedIn URL', 'type' => 'url', 'group' => 'Social Media'],
        'instagram_url' => ['label' => 'Instagram URL', 'type' => 'url', 'group' => 'Social Media'],
        'youtube_url' => ['label' => 'YouTube URL', 'type' => 'url', 'group' => 'Social Media'],
        'meta_title' => ['label' => 'Default SEO Title', 'type' => 'text', 'group' => 'SEO'],
        'meta_description' => ['label' => 'Default SEO Description', 'type' => 'textarea', 'group' => 'SEO'],
    ],
];
